/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Recharge = IDL.Record({
  'id' : IDL.Nat,
  'validity' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Int,
  'operator' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Nat,
  'planName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRecharges' : IDL.Func([], [IDL.Vec(Recharge)], ['query']),
  'getRecharge' : IDL.Func([IDL.Nat], [Recharge], ['query']),
  'getRechargeHistory' : IDL.Func([IDL.Text], [IDL.Vec(Recharge)], ['query']),
  'submitRecharge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Recharge = IDL.Record({
    'id' : IDL.Nat,
    'validity' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Int,
    'operator' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Nat,
    'planName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRecharges' : IDL.Func([], [IDL.Vec(Recharge)], ['query']),
    'getRecharge' : IDL.Func([IDL.Nat], [Recharge], ['query']),
    'getRechargeHistory' : IDL.Func([IDL.Text], [IDL.Vec(Recharge)], ['query']),
    'submitRecharge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };